backend:
  name: github
  repo: dulakshijayasundara08-blip/my-cms-site
  branch: main
  site_domain: my-cms-site-eta.vercel.app
  base_url: https://my-cms-site-eta.vercel.app
  auth_endpoint: /api/auth

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }